#include "Config.h"
#include "../../third_party/jsonic/json.h"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <regex>
#include <set>
#include <sstream>
namespace fs=std::filesystem;
namespace tscc { namespace {
std::string slash(std::string s){std::replace(s.begin(),s.end(),'\\','/');return s;}
bool glob(const std::string&p0,const std::string&v0){auto p=slash(p0),v=slash(v0);std::string r="^";for(std::size_t i=0;i<p.size();++i){char c=p[i];if(c=='*'){if(i+1<p.size()&&p[i+1]=='*'){++i;if(i+1<p.size()&&p[i+1]=='/'){++i;r+="(?:.*/)?";}else r+=".*";}else r+="[^/]*";}else if(c=='?')r+="[^/]";else{if(std::string(".^$|()[]{}+\\").find(c)!=std::string::npos)r+='\\';r+=c;}}return std::regex_match(v,std::regex(r+"$"));}
bool matches(const std::vector<std::string>&p,const std::string&v){for(const auto&x:p)if(glob(x,v))return true;return false;}
const json::Document* member(const json::Document&v,const std::string&k){if(!v.is_object())return nullptr;for(auto i=v.object.rbegin();i!=v.object.rend();++i)if(i->first==k)return &i->second;return nullptr;}
bool strings(const json::Document*v,std::vector<std::string>&out){if(!v||!v->is_array())return false;out.clear();for(const auto&x:v->array){if(!x.is_string())return false;out.push_back(x.string);}return true;}
struct Select{std::vector<std::string>files,include,exclude;fs::path dir;};
bool load(const fs::path&file,CompilerOptions&o,Select&s,Diagnostics&d,std::set<std::string>&active){std::error_code ec;auto path=fs::absolute(file,ec).lexically_normal();auto id=path.string();if(!active.insert(id).second){d.error(id,1,1,"configuration inheritance cycle",{},"TSCC3002");return false;}std::ifstream in(path,std::ios::binary);if(!in){d.error(id,1,1,"cannot read project configuration");active.erase(id);return false;}std::ostringstream buf;buf<<in.rdbuf();auto text=buf.str();json::Document root;json::ParseDiagnostic e;json::ParseOptions po;po.allow_comments=true;po.allow_trailing_commas=true;po.duplicate_keys=json::DuplicateKeyPolicy::Reject;if(!json::Document::parse(text,root,e,po)){d.error(id,e.line,e.column,e.message,{},"TSCC3002");active.erase(id);return false;}if(!root.is_object()){d.error(id,1,1,"project configuration must be an object",{},"TSCC3002");active.erase(id);return false;}auto dir=path.parent_path();if(auto*x=member(root,"extends")){if(!x->is_string()){d.error(id,1,1,"'extends' must be a string",{},"TSCC3002");active.erase(id);return false;}auto parent=dir/x->string;if(!parent.has_extension())parent += ".json";if(!load(parent,o,s,d,active)){active.erase(id);return false;}}
if(auto*c=member(root,"compilerOptions")){if(!c->is_object()){d.error(id,1,1,"'compilerOptions' must be an object",{},"TSCC3002");active.erase(id);return false;}std::vector<std::string>known={"outDir","rootDir","target","module","moduleResolution","jsx","removeComments","noEmit","noEmitOnError","noLib","baseUrl","paths","rootDirs","lib","types"};for(const auto&x:c->object)if(std::find(known.begin(),known.end(),x.first)==known.end()){d.error(id,1,1,"unsupported compiler option '"+x.first+"'",{},"TSCC3001");active.erase(id);return false;}auto str=[&](const char*k,std::string&t,bool p=false){if(auto*x=member(*c,k)){if(!x->is_string()){d.error(id,1,1,"compiler option '"+std::string(k)+"' must be a string",{},"TSCC3002");return false;}t=p?(dir/x->string).lexically_normal().string():x->string;}return true;};if(!str("outDir",o.out_dir,true)||!str("rootDir",o.root_dir,true)||!str("target",o.target)||!str("module",o.module)||!str("moduleResolution",o.module_resolution)||!str("jsx",o.jsx)||!str("baseUrl",o.base_url,true)){active.erase(id);return false;}for(auto k:{"removeComments","noEmit","noEmitOnError","noLib"})if(auto*x=member(*c,k)){if(!x->is_bool()){d.error(id,1,1,"compiler option '"+std::string(k)+"' must be boolean",{},"TSCC3002");active.erase(id);return false;}if(std::string(k)=="removeComments")o.remove_comments=x->boolean;else if(std::string(k)=="noEmit")o.no_emit=x->boolean;else if(std::string(k)=="noEmitOnError")o.no_emit_on_error=x->boolean;else{o.no_lib=x->boolean;if(x->boolean)o.lib.clear();}}for(auto pair:{std::pair<const char*,std::vector<std::string>*>("lib",&o.lib),{"types",&o.types}})if(auto*x=member(*c,pair.first)){if(!strings(x,*pair.second)){d.error(id,1,1,"compiler option '"+std::string(pair.first)+"' must be an array of strings",{},"TSCC3002");active.erase(id);return false;}}if(auto*x=member(*c,"rootDirs")){std::vector<std::string>v;if(!strings(x,v)){d.error(id,1,1,"compiler option 'rootDirs' must be an array of strings",{},"TSCC3002");active.erase(id);return false;}o.root_dirs.clear();for(auto&q:v)o.root_dirs.push_back((dir/q).lexically_normal().string());}if(auto*x=member(*c,"paths")){if(!x->is_object()){d.error(id,1,1,"compiler option 'paths' must be an object",{},"TSCC3002");active.erase(id);return false;}o.paths.clear();for(const auto&m:x->object){std::vector<std::string>v;if(!strings(&m.second,v)){d.error(id,1,1,"path mapping '"+m.first+"' must be an array of strings",{},"TSCC3002");active.erase(id);return false;}o.paths.push_back({m.first,std::move(v)});}}}
for(auto k:{"files","include","exclude"})if(auto*x=member(root,k)){std::vector<std::string>v;if(!strings(x,v)){d.error(id,1,1,"'"+std::string(k)+"' must be an array of strings",{},"TSCC3002");active.erase(id);return false;}auto&t=std::string(k)=="files"?s.files:std::string(k)=="include"?s.include:s.exclude;t=std::move(v);s.dir=dir;}
if(s.dir.empty())s.dir=dir;
active.erase(id);return true;}
}
bool load_tsconfig(const std::string&path,CompilerOptions&o,std::vector<std::string>&roots,Diagnostics&d){Select s;std::set<std::string>a;if(!load(path,o,s,d,a))return false;auto dir=s.dir;roots.clear();if(!s.files.empty())for(const auto&x:s.files)roots.push_back((dir/x).lexically_normal().string());else{std::error_code ec;auto out=o.out_dir.empty()?fs::path():fs::absolute(o.out_dir,ec).lexically_normal();for(fs::recursive_directory_iterator i(dir,fs::directory_options::skip_permission_denied,ec),end;i!=end;i.increment(ec)){if(ec){ec.clear();continue;}auto p=i->path();if(i->is_directory()){auto n=p.filename().string();if(n=="node_modules"||n==".git"||(!out.empty()&&fs::absolute(p,ec).lexically_normal()==out))i.disable_recursion_pending();continue;}if(i->is_regular_file()&&(p.extension()==".ts"||p.extension()==".tsx")&&p.filename().string().find(".d.ts")==std::string::npos){std::error_code re;auto rel=slash(fs::relative(p,dir,re).string());if((s.include.empty()||matches(s.include,rel))&&!matches(s.exclude,rel))roots.push_back(p.string());}}}std::sort(roots.begin(),roots.end());if(roots.empty()){d.error(path,1,1,"project contains no TypeScript input files");return false;}if(o.root_dir.empty())o.root_dir=dir.string();return true;}
}
