#include "ControlFlow.h"
#include <algorithm>
#include <queue>
namespace tscc { namespace {
std::size_t matching(const std::vector<Token>&t,std::size_t open,const char*l,const char*r,std::size_t limit){int depth=0;for(std::size_t i=open;i<limit;++i){if(t[i].text==l)++depth;else if(t[i].text==r&&--depth==0)return i;}return limit;}
BasicBlockKind kind_for(const std::string&s){if(s=="if"||s=="switch")return BasicBlockKind::Branch;if(s=="for"||s=="while"||s=="do")return BasicBlockKind::Loop;if(s=="return")return BasicBlockKind::Return;if(s=="throw")return BasicBlockKind::Throw;if(s=="try")return BasicBlockKind::Try;if(s=="catch")return BasicBlockKind::Catch;if(s=="finally")return BasicBlockKind::Finally;return BasicBlockKind::Statement;}
struct Candidate{std::size_t begin,end;BasicBlockKind kind;};
void add_edge(FunctionControlFlow&g,BasicBlockId from,BasicBlockId to,ControlFlowEdgeKind kind){if(from>=g.blocks.size()||to>=g.blocks.size())return;for(const auto&e:g.edges)if(e.from==from&&e.to==to&&e.kind==kind)return;g.edges.push_back({from,to,kind});}
void finalize(FunctionControlFlow&g){for(auto&b:g.blocks)b.predecessors.clear();for(const auto&e:g.edges)g.blocks[e.to].predecessors.push_back(e.from);for(auto&b:g.blocks){std::sort(b.predecessors.begin(),b.predecessors.end());b.predecessors.erase(std::unique(b.predecessors.begin(),b.predecessors.end()),b.predecessors.end());}std::queue<BasicBlockId>q;g.blocks[g.entry].reachable=true;q.push(g.entry);while(!q.empty()){auto from=q.front();q.pop();for(const auto&e:g.edges)if(e.from==from&&!g.blocks[e.to].reachable){g.blocks[e.to].reachable=true;q.push(e.to);}}}
std::vector<std::size_t> significant(const std::vector<Token>&tokens,std::size_t begin,std::size_t end){std::vector<std::size_t>out;for(auto i=begin;i<end;++i)if(tokens[i].kind!=TokenKind::Comment)out.push_back(i);return out;}
std::vector<FlowPredicate> predicates(const std::vector<Token>&tokens,std::size_t begin,std::size_t end){std::vector<FlowPredicate>out;auto all=significant(tokens,begin,end);std::size_t part=0;for(std::size_t i=0;i<=all.size();++i){if(i<all.size()&&tokens[all[i]].text!="&&")continue;std::vector<std::size_t>s(all.begin()+part,all.begin()+i);part=i+1;if(s.empty())continue;bool negated=false;if(tokens[s.front()].text=="!"){negated=true;s.erase(s.begin());}FlowPredicate p;p.negated=negated;if(s.size()==1&&tokens[s[0]].kind==TokenKind::Identifier){p.kind=FlowPredicateKind::Truthy;p.reference_token=s[0];out.push_back(p);}else if(s.size()==4&&tokens[s[0]].text=="typeof"&&tokens[s[1]].kind==TokenKind::Identifier&&(tokens[s[2]].text=="==="||tokens[s[2]].text=="!==")&&tokens[s[3]].kind==TokenKind::String){p.kind=FlowPredicateKind::Typeof;p.reference_token=s[1];p.value_token=s[3];p.negated=p.negated||(tokens[s[2]].text=="!==");out.push_back(p);}else if(s.size()==3&&tokens[s[0]].kind==TokenKind::Identifier&&(tokens[s[1]].text=="==="||tokens[s[1]].text=="!==")){p.kind=FlowPredicateKind::Equality;p.reference_token=s[0];p.value_token=s[2];p.negated=p.negated||(tokens[s[1]].text=="!==");out.push_back(p);}else if(s.size()==5&&tokens[s[0]].kind==TokenKind::Identifier&&tokens[s[1]].text=="."&&tokens[s[2]].kind==TokenKind::Identifier&&(tokens[s[3]].text=="==="||tokens[s[3]].text=="!==")){p.kind=FlowPredicateKind::Discriminant;p.reference_token=s[0];p.property_token=s[2];p.value_token=s[4];p.negated=p.negated||(tokens[s[3]].text=="!==");out.push_back(p);}else if(s.size()==3&&tokens[s[0]].kind==TokenKind::Identifier&&tokens[s[1]].text=="instanceof"&&tokens[s[2]].kind==TokenKind::Identifier){p.kind=FlowPredicateKind::Instanceof;p.reference_token=s[0];p.value_token=s[2];out.push_back(p);}else if(s.size()==3&&tokens[s[0]].kind==TokenKind::String&&tokens[s[1]].text=="in"&&tokens[s[2]].kind==TokenKind::Identifier){p.kind=FlowPredicateKind::PropertyPresence;p.reference_token=s[2];p.value_token=s[0];out.push_back(p);}}return out;}
}
ControlFlowModel build_control_flow(const std::vector<Token>&tokens,const SemanticModel&semantic,const ExpressionModel&expressions){ControlFlowModel result;
 for(const auto&function:semantic.nodes){if(function.kind!=SemanticNodeKind::FunctionDeclaration&&function.kind!=SemanticNodeKind::ArrowFunction)continue;std::size_t begin=function.scope_token,end=function.end_token;if(begin>=tokens.size()||end<=begin)continue;if(tokens[begin].text=="{"){++begin;if(end&&tokens[end-1].text=="}")--end;}FunctionControlFlow g;g.function_node=function.id;g.blocks.push_back({0,BasicBlockKind::Entry,begin,begin,{},false});std::vector<Candidate>items;
  for(const auto&node:semantic.nodes)if(node.kind==SemanticNodeKind::Statement&&node.begin_token>=begin&&node.end_token<=end)items.push_back({node.begin_token,node.end_token,kind_for(tokens[node.begin_token].text)});
  for(std::size_t p=begin;p<end;++p){const auto k=kind_for(tokens[p].text);if(k!=BasicBlockKind::Statement)items.push_back({p,p+1,k});}
  for(const auto&node:semantic.nodes)if(node.kind==SemanticNodeKind::Condition&&node.begin_token>=begin&&node.end_token<=end&&node.expression_id<expressions.nodes().size()){std::vector<ExpressionId>pending{node.expression_id};while(!pending.empty()){const auto id=pending.back();pending.pop_back();const auto&e=expressions.node(id);if(e.kind==ExpressionKind::Binary&&(e.text=="&&"||e.text=="||"||e.text=="??"))items.push_back({e.operator_token,e.operator_token+1,BasicBlockKind::ShortCircuit});pending.insert(pending.end(),e.children.begin(),e.children.end());}}
  std::sort(items.begin(),items.end(),[](const auto&a,const auto&b){if(a.begin!=b.begin)return a.begin<b.begin;if(a.kind!=b.kind)return static_cast<int>(a.kind)<static_cast<int>(b.kind);return a.end<b.end;});items.erase(std::unique(items.begin(),items.end(),[](const auto&a,const auto&b){return a.begin==b.begin&&a.kind==b.kind;}),items.end());for(const auto&i:items){const auto id=g.blocks.size();g.blocks.push_back({id,i.kind,i.begin,i.end,{},false});}g.exit=g.blocks.size();g.blocks.push_back({g.exit,BasicBlockKind::Exit,end,end,{},false});
  BasicBlockId previous=g.entry;for(BasicBlockId id=1;id<g.exit;++id){if(g.blocks[previous].kind!=BasicBlockKind::Return&&g.blocks[previous].kind!=BasicBlockKind::Throw)add_edge(g,previous,id,ControlFlowEdgeKind::Normal);previous=id;}if(g.blocks[previous].kind!=BasicBlockKind::Return&&g.blocks[previous].kind!=BasicBlockKind::Throw)add_edge(g,previous,g.exit,ControlFlowEdgeKind::Normal);
  for(BasicBlockId id=1;id<g.exit;++id){auto&block=g.blocks[id];if(block.kind==BasicBlockKind::Return){g.edges.erase(std::remove_if(g.edges.begin(),g.edges.end(),[&](const auto&e){return e.from==id;}),g.edges.end());add_edge(g,id,g.exit,ControlFlowEdgeKind::Normal);}else if(block.kind==BasicBlockKind::Throw){g.edges.erase(std::remove_if(g.edges.begin(),g.edges.end(),[&](const auto&e){return e.from==id;}),g.edges.end());BasicBlockId target=g.exit;for(BasicBlockId q=id+1;q<g.exit;++q)if(g.blocks[q].kind==BasicBlockKind::Catch){target=q;break;}add_edge(g,id,target,target==g.exit?ControlFlowEdgeKind::Exception:ControlFlowEdgeKind::Exception);}else if(block.kind==BasicBlockKind::Branch||block.kind==BasicBlockKind::Loop){if(id+1<=g.exit)add_edge(g,id,id+1,ControlFlowEdgeKind::TrueBranch);std::size_t open=block.begin_token+1;while(open<end&&tokens[open].text!="(")++open;auto close=open<end?matching(tokens,open,"(",")",end):end;std::size_t body=close<end?close+1:end,after=body;if(body<end&&tokens[body].text=="{")after=matching(tokens,body,"{","}",end)+1;BasicBlockId after_id=g.exit,last=id;for(BasicBlockId q=id+1;q<g.exit;++q){if(g.blocks[q].begin_token<after)last=q;else{after_id=q;break;}}add_edge(g,id,after_id,ControlFlowEdgeKind::FalseBranch);if(block.kind==BasicBlockKind::Loop&&last!=id)add_edge(g,last,id,ControlFlowEdgeKind::BackEdge);}else if(block.kind==BasicBlockKind::ShortCircuit&&id+1<=g.exit)add_edge(g,id,id+1,ControlFlowEdgeKind::ShortCircuit);else if(block.kind==BasicBlockKind::Try){for(BasicBlockId q=id+1;q<g.exit;++q)if(g.blocks[q].kind==BasicBlockKind::Catch){add_edge(g,id,q,ControlFlowEdgeKind::Exception);break;}}else if(block.kind==BasicBlockKind::Catch){for(BasicBlockId q=id+1;q<g.exit;++q)if(g.blocks[q].kind==BasicBlockKind::Finally){add_edge(g,id,q,ControlFlowEdgeKind::Finally);break;}}}
  for(std::size_t p=begin;p<end;++p){const bool loop=tokens[p].text=="while"||tokens[p].text=="for";if(tokens[p].text!="if"&&!loop)continue;std::size_t open=p+1;while(open<end&&tokens[open].kind==TokenKind::Comment)++open;if(open>=end||tokens[open].text!="(")continue;const auto close=matching(tokens,open,"(",")",end);if(close>=end)continue;auto predicate=predicates(tokens,open+1,close);if(predicate.empty())continue;std::size_t body=close+1;while(body<end&&tokens[body].kind==TokenKind::Comment)++body;std::size_t body_end=body+1;if(body<end&&tokens[body].text=="{")body_end=matching(tokens,body,"{","}",end);if(body_end>end)continue;g.flow_regions.push_back({body<end&&tokens[body].text=="{"?body+1:body,body_end,true,loop,predicate});std::size_t otherwise=body_end+(body<end&&tokens[body].text=="{"?1:0);while(otherwise<end&&tokens[otherwise].kind==TokenKind::Comment)++otherwise;if(!loop&&otherwise<end&&tokens[otherwise].text=="else"){auto alternate=otherwise+1;while(alternate<end&&tokens[alternate].kind==TokenKind::Comment)++alternate;auto alternate_end=alternate+1;if(alternate<end&&tokens[alternate].text=="{")alternate_end=matching(tokens,alternate,"{","}",end);g.flow_regions.push_back({alternate<end&&tokens[alternate].text=="{"?alternate+1:alternate,alternate_end,false,false,predicate});}}
  finalize(g);result.functions.push_back(std::move(g));}
 for(std::size_t p=0;p<tokens.size();++p){const bool loop=tokens[p].text=="while"||tokens[p].text=="for";if(tokens[p].text!="if"&&!loop)continue;std::size_t open=p+1;while(open<tokens.size()&&tokens[open].kind==TokenKind::Comment)++open;if(open>=tokens.size()||tokens[open].text!="(")continue;const auto close=matching(tokens,open,"(",")",tokens.size());if(close>=tokens.size())continue;auto predicate=predicates(tokens,open+1,close);if(predicate.empty())continue;std::size_t body=close+1;while(body<tokens.size()&&tokens[body].kind==TokenKind::Comment)++body;std::size_t body_end=body+1;if(body<tokens.size()&&tokens[body].text=="{")body_end=matching(tokens,body,"{","}",tokens.size());if(body_end>tokens.size())continue;result.flow_regions.push_back({body<tokens.size()&&tokens[body].text=="{"?body+1:body,body_end,true,loop,predicate});std::size_t otherwise=body_end+(body<tokens.size()&&tokens[body].text=="{"?1:0);while(otherwise<tokens.size()&&tokens[otherwise].kind==TokenKind::Comment)++otherwise;if(!loop&&otherwise<tokens.size()&&tokens[otherwise].text=="else"){auto alternate=otherwise+1;while(alternate<tokens.size()&&tokens[alternate].kind==TokenKind::Comment)++alternate;auto alternate_end=alternate+1;if(alternate<tokens.size()&&tokens[alternate].text=="{")alternate_end=matching(tokens,alternate,"{","}",tokens.size());result.flow_regions.push_back({alternate<tokens.size()&&tokens[alternate].text=="{"?alternate+1:alternate,alternate_end,false,false,predicate});}}
 if(result.functions.empty()&&!result.flow_regions.empty()){FunctionControlFlow global;global.function_node=InvalidSemanticNodeId;result.functions.push_back(std::move(global));}for(auto&graph:result.functions)graph.flow_regions.insert(graph.flow_regions.end(),result.flow_regions.begin(),result.flow_regions.end());return result;}
}
