#include "ControlFlow.h"
#include <algorithm>
#include <queue>
namespace tscc { namespace {
std::size_t matching(const std::vector<Token>&t,std::size_t open,const char*l,const char*r,std::size_t limit){int depth=0;for(std::size_t i=open;i<limit;++i){if(t[i].text==l)++depth;else if(t[i].text==r&&--depth==0)return i;}return limit;}
BasicBlockKind kind_for(const std::string&s){if(s=="if"||s=="switch")return BasicBlockKind::Branch;if(s=="for"||s=="while"||s=="do")return BasicBlockKind::Loop;if(s=="return")return BasicBlockKind::Return;if(s=="throw")return BasicBlockKind::Throw;if(s=="try")return BasicBlockKind::Try;if(s=="catch")return BasicBlockKind::Catch;if(s=="finally")return BasicBlockKind::Finally;return BasicBlockKind::Statement;}
struct Candidate{std::size_t begin,end;BasicBlockKind kind;};
void add_edge(FunctionControlFlow&g,BasicBlockId from,BasicBlockId to,ControlFlowEdgeKind kind){if(from>=g.blocks.size()||to>=g.blocks.size())return;for(const auto&e:g.edges)if(e.from==from&&e.to==to&&e.kind==kind)return;g.edges.push_back({from,to,kind});}
void finalize(FunctionControlFlow&g){for(auto&b:g.blocks)b.predecessors.clear();for(const auto&e:g.edges)g.blocks[e.to].predecessors.push_back(e.from);for(auto&b:g.blocks){std::sort(b.predecessors.begin(),b.predecessors.end());b.predecessors.erase(std::unique(b.predecessors.begin(),b.predecessors.end()),b.predecessors.end());}std::queue<BasicBlockId>q;g.blocks[g.entry].reachable=true;q.push(g.entry);while(!q.empty()){auto from=q.front();q.pop();for(const auto&e:g.edges)if(e.from==from&&!g.blocks[e.to].reachable){g.blocks[e.to].reachable=true;q.push(e.to);}}}
}
ControlFlowModel build_control_flow(const std::vector<Token>&tokens,const SemanticModel&semantic,const ExpressionModel&expressions){ControlFlowModel result;
 for(const auto&function:semantic.nodes){if(function.kind!=SemanticNodeKind::FunctionDeclaration&&function.kind!=SemanticNodeKind::ArrowFunction)continue;std::size_t begin=function.scope_token,end=function.end_token;if(begin>=tokens.size()||end<=begin)continue;if(tokens[begin].text=="{"){++begin;if(end&&tokens[end-1].text=="}")--end;}FunctionControlFlow g;g.function_node=function.id;g.blocks.push_back({0,BasicBlockKind::Entry,begin,begin,{},false});std::vector<Candidate>items;
  for(const auto&node:semantic.nodes)if(node.kind==SemanticNodeKind::Statement&&node.begin_token>=begin&&node.end_token<=end)items.push_back({node.begin_token,node.end_token,kind_for(tokens[node.begin_token].text)});
  for(std::size_t p=begin;p<end;++p){const auto k=kind_for(tokens[p].text);if(k!=BasicBlockKind::Statement)items.push_back({p,p+1,k});}
  for(const auto&node:semantic.nodes)if(node.kind==SemanticNodeKind::Condition&&node.begin_token>=begin&&node.end_token<=end&&node.expression_id<expressions.nodes().size()){std::vector<ExpressionId>pending{node.expression_id};while(!pending.empty()){const auto id=pending.back();pending.pop_back();const auto&e=expressions.node(id);if(e.kind==ExpressionKind::Binary&&(e.text=="&&"||e.text=="||"||e.text=="??"))items.push_back({e.operator_token,e.operator_token+1,BasicBlockKind::ShortCircuit});pending.insert(pending.end(),e.children.begin(),e.children.end());}}
  std::sort(items.begin(),items.end(),[](const auto&a,const auto&b){if(a.begin!=b.begin)return a.begin<b.begin;if(a.kind!=b.kind)return static_cast<int>(a.kind)<static_cast<int>(b.kind);return a.end<b.end;});items.erase(std::unique(items.begin(),items.end(),[](const auto&a,const auto&b){return a.begin==b.begin&&a.kind==b.kind;}),items.end());for(const auto&i:items){const auto id=g.blocks.size();g.blocks.push_back({id,i.kind,i.begin,i.end,{},false});}g.exit=g.blocks.size();g.blocks.push_back({g.exit,BasicBlockKind::Exit,end,end,{},false});
  BasicBlockId previous=g.entry;for(BasicBlockId id=1;id<g.exit;++id){if(g.blocks[previous].kind!=BasicBlockKind::Return&&g.blocks[previous].kind!=BasicBlockKind::Throw)add_edge(g,previous,id,ControlFlowEdgeKind::Normal);previous=id;}if(g.blocks[previous].kind!=BasicBlockKind::Return&&g.blocks[previous].kind!=BasicBlockKind::Throw)add_edge(g,previous,g.exit,ControlFlowEdgeKind::Normal);
  for(BasicBlockId id=1;id<g.exit;++id){auto&block=g.blocks[id];if(block.kind==BasicBlockKind::Return){g.edges.erase(std::remove_if(g.edges.begin(),g.edges.end(),[&](const auto&e){return e.from==id;}),g.edges.end());add_edge(g,id,g.exit,ControlFlowEdgeKind::Normal);}else if(block.kind==BasicBlockKind::Throw){g.edges.erase(std::remove_if(g.edges.begin(),g.edges.end(),[&](const auto&e){return e.from==id;}),g.edges.end());BasicBlockId target=g.exit;for(BasicBlockId q=id+1;q<g.exit;++q)if(g.blocks[q].kind==BasicBlockKind::Catch){target=q;break;}add_edge(g,id,target,target==g.exit?ControlFlowEdgeKind::Exception:ControlFlowEdgeKind::Exception);}else if(block.kind==BasicBlockKind::Branch||block.kind==BasicBlockKind::Loop){if(id+1<=g.exit)add_edge(g,id,id+1,ControlFlowEdgeKind::TrueBranch);std::size_t open=block.begin_token+1;while(open<end&&tokens[open].text!="(")++open;auto close=open<end?matching(tokens,open,"(",")",end):end;std::size_t body=close<end?close+1:end,after=body;if(body<end&&tokens[body].text=="{")after=matching(tokens,body,"{","}",end)+1;BasicBlockId after_id=g.exit,last=id;for(BasicBlockId q=id+1;q<g.exit;++q){if(g.blocks[q].begin_token<after)last=q;else{after_id=q;break;}}add_edge(g,id,after_id,ControlFlowEdgeKind::FalseBranch);if(block.kind==BasicBlockKind::Loop&&last!=id)add_edge(g,last,id,ControlFlowEdgeKind::BackEdge);}else if(block.kind==BasicBlockKind::ShortCircuit&&id+1<=g.exit)add_edge(g,id,id+1,ControlFlowEdgeKind::ShortCircuit);else if(block.kind==BasicBlockKind::Try){for(BasicBlockId q=id+1;q<g.exit;++q)if(g.blocks[q].kind==BasicBlockKind::Catch){add_edge(g,id,q,ControlFlowEdgeKind::Exception);break;}}else if(block.kind==BasicBlockKind::Catch){for(BasicBlockId q=id+1;q<g.exit;++q)if(g.blocks[q].kind==BasicBlockKind::Finally){add_edge(g,id,q,ControlFlowEdgeKind::Finally);break;}}}
  finalize(g);result.functions.push_back(std::move(g));}
 return result;}
}
