#include "JSX.h"
#include "TypeParser.h"
#include <algorithm>
#include <unordered_set>
namespace tscc { namespace {
constexpr std::size_t bad=static_cast<std::size_t>(-1);
void report(CompilationUnit&u,std::size_t token,const std::string&message){if(token>=u.tokens.size())token=u.tokens.size()-1;auto lc=u.source.line_col(u.tokens[token].begin);u.diagnostics.error(u.source.path,lc.first,lc.second,message,u.source.line_text(lc.first),"TSCC4001");}
std::size_t matching(const std::vector<Token>&t,std::size_t at,const std::string&open,const std::string&close){int depth=0;for(;at<t.size();++at){if(t[at].text==open)++depth;else if(t[at].text==close&&--depth==0)return at;}return bad;}
TypeId intrinsic_contract(CompilationUnit&u){const auto&t=u.tokens;for(std::size_t i=0;i+3<t.size();++i){if(t[i].text!="namespace"||t[i+1].text!="JSX")continue;auto open=i+2;while(open<t.size()&&t[open].text!="{")++open;auto close=matching(t,open,"{","}");if(close==bad)continue;for(auto p=open+1;p+2<close;++p){if(t[p].text!="interface"||t[p+1].text!="IntrinsicElements")continue;auto body=p+2;while(body<close&&t[body].text!="{")++body;auto end=matching(t,body,"{","}");if(end==bad||end>close)continue;auto at=body;return parse_type_annotation(t,at,end+1,u.types.store,&u.types.named_types);}}return u.types.store.unknown();}
TypeId simple_value(CompilationUnit&u,std::size_t begin,std::size_t end){while(begin<end&&u.tokens[begin].kind==TokenKind::Comment)++begin;if(begin>=end)return u.types.store.boolean();const auto&x=u.tokens[begin];if(x.kind==TokenKind::String)return u.types.store.string();if(x.kind==TokenKind::Number)return !x.text.empty()&&x.text.back()=='n'?u.types.store.bigint():u.types.store.number();if(x.text=="true"||x.text=="false")return u.types.store.boolean();if(x.text=="null")return u.types.store.null();if(x.kind==TokenKind::Identifier){auto symbol=u.binding.symbol_for_reference(begin);if(symbol<u.types.symbol_types.size())return u.types.symbol_types[symbol];}return u.types.store.unknown();}
TypeId component_props(CompilationUnit&u,std::size_t name){auto symbol=u.binding.symbol_for_reference(name);if(symbol>=u.types.symbol_types.size())return u.types.store.unknown();if(const auto*call=u.types.store.callable(u.types.symbol_types[symbol]))return call->parameters.empty()?u.types.store.object_of({}):call->parameters.front();return u.types.store.unknown();}
}
bool check_jsx_semantics(CompilationUnit&u){const auto&t=u.tokens;const auto intrinsic=intrinsic_contract(u);bool ok=true;for(std::size_t i=0;i+1<t.size();++i){if(t[i].text!="<"||t[i+1].text=="/"||t[i+1].text==">")continue;if(t[i+1].kind!=TokenKind::Identifier&&t[i+1].kind!=TokenKind::Keyword)continue;const auto name_token=i+1;const auto name=t[name_token].text;auto p=name_token+1;while(p<t.size()&&(t[p].text=="."||t[p].kind==TokenKind::Identifier)&&t[p].begin==t[p-1].end)++p;if(p<t.size()&&t[p].text=="<"&&t[p].begin==t[p-1].end){auto generic=matching(t,p,"<",">");if(generic==bad)continue;p=generic+1;}int braces=0;auto end=p;for(;end<t.size();++end){if(t[end].text=="{")++braces;else if(t[end].text=="}"&&braces)--braces;else if(t[end].text==">"&&!braces)break;}if(end>=t.size())continue;TypeId props=u.types.store.unknown();if(!name.empty()&&name.front()>='a'&&name.front()<='z'){if(intrinsic==u.types.store.unknown())continue;const auto*entry=u.types.store.property(intrinsic,name);if(!entry){report(u,name_token,"JSX intrinsic element '"+name+"' is not declared by JSX.IntrinsicElements.");ok=false;continue;}props=entry->type;}else{props=component_props(u,name_token);if(props==u.types.store.unknown()){report(u,name_token,"JSX component '"+name+"' is not callable with a props contract.");ok=false;continue;}}std::unordered_set<std::string>present;for(auto a=p;a<end;){if(t[a].kind==TokenKind::Comment||t[a].text=="/"){++a;continue;}if(t[a].text=="{"){auto close=matching(t,a,"{","}");a=close==bad?end:close+1;continue;}if(t[a].kind!=TokenKind::Identifier&&t[a].kind!=TokenKind::Keyword){++a;continue;}auto attr=t[a].text;present.insert(attr);auto attr_token=a++;TypeId actual=u.types.store.boolean();if(a<end&&t[a].text=="="){++a;if(a<end&&t[a].text=="{"){auto close=matching(t,a,"{","}");actual=close==bad?u.types.store.unknown():simple_value(u,a+1,close);a=close==bad?end:close+1;}else{actual=simple_value(u,a,std::min(a+1,end));++a;}}const auto*expected=u.types.store.property(props,attr);if(!expected){report(u,attr_token,"Property '"+attr+"' does not exist on JSX props type '"+u.types.store.name(props)+"'.");ok=false;}else if(actual!=u.types.store.unknown()&&!u.types.store.assignable(actual,expected->type)){report(u,attr_token,"Type '"+u.types.store.name(actual)+"' is not assignable to JSX property '"+attr+"' of type '"+u.types.store.name(expected->type)+"'.");ok=false;}}const bool self_closing=end>0&&t[end-1].text=="/";for(const auto&property:u.types.store.properties(props))if(!property.optional&&!present.count(property.name)&&(property.name!="children"||self_closing)){report(u,name_token,"JSX property '"+property.name+"' is required.");ok=false;}i=end;}return ok;}
}
